version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:16.13-alpine
  working_dir: /omeda
  restart: always
  volumes:
    - .:/omeda:cached
    - ./node_modules:/omeda/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "9910:27017"

  redis:
    tty: true
    image: redis:6.2-alpine
    ports:
      - "9911:6379"

  graphql:
    <<: *node
    working_dir: /omeda/services/graphql
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      MONGO_URI: ${MONGO_URI-mongodb://mongodb:27017}
    depends_on:
      - mongodb
      - redis
    ports:
      - "8990:8990"

  cli:
    <<: *node
    working_dir: /omeda/services/cli
    entrypoint: ["node"]
    command: ["src/index.js"]
    environment:
      <<: *env
      OMEDA_APP_ID: ${OMEDA_APP_ID-}
      OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-}
      OMEDA_BRAND_KEY: ${OMEDA_BRAND_KEY-}
      OMEDA_CLIENT_KEY: ${OMEDA_CLIENT_KEY-}

volumes:
  yarn-cache: {}
  mongodb: {}
